name: Runner Test

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/runner-test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity
        run: echo "runner works"
